/**
 * ABI for StubbyRaffle.
 *
 * GENERATED by scripts/generate-abi.mjs — do not edit. Run `pnpm generate:abi`
 * after changing the contract.
 */
export const stubbyRaffleAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'usdc',
        type: 'address',
        internalType: 'contract IERC20',
      },
      {
        name: 'randomness_',
        type: 'address',
        internalType: 'contract IRandomnessSource',
      },
      {
        name: 'treasury_',
        type: 'address',
        internalType: 'address',
      },
      {
        name: 'owner_',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'MAX_ENTRIES_PER_WALLET',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_RANDOMNESS_TIMEOUT',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_PRIZE',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_RANDOMNESS_TIMEOUT',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'RANDOMNESS_SOURCE_DELAY',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IERC20',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'acceptOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'activateRandomnessSource',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'buyerOfEntry',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'index',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelRaffle',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelRandomnessSource',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claim',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimTo',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'recipient',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'closeEarly',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collected',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createRaffle',
    inputs: [
      {
        name: 'prize',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'entryPrice',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'totalEntries',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'windowSeconds',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'enter',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'count',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'entriesOf',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'wallet',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'entriesPaused',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'extendWindow',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fulfillRandomness',
    inputs: [
      {
        name: 'requestId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'randomWord',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getRaffle',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct StubbyRaffle.Raffle',
        components: [
          {
            name: 'prize',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'entryPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'topUp',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'prizeOwed',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'commissionOwed',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'requestId',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'totalEntries',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'entriesSold',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'winningEntry',
            type: 'uint32',
            internalType: 'uint32',
          },
          {
            name: 'windowEnds',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'windowSeconds',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'requestedAt',
            type: 'uint64',
            internalType: 'uint64',
          },
          {
            name: 'winner',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'source',
            type: 'address',
            internalType: 'address',
          },
          {
            name: 'status',
            type: 'uint8',
            internalType: 'enum StubbyRaffle.Status',
          },
          {
            name: 'prizePaid',
            type: 'bool',
            internalType: 'bool',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isPrizeCovered',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextRaffleId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextRequestId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingOwner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingRandomness',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingRandomnessAt',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'raffleOfRequest',
    inputs: [
      {
        name: 'requestId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'randomness',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IRandomnessSource',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'randomnessTimeout',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reRequestRandomness',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'requiredHoldings',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'segmentCount',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setEntriesPaused',
    inputs: [
      {
        name: 'paused',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setRandomnessSource',
    inputs: [
      {
        name: 'source',
        type: 'address',
        internalType: 'contract IRandomnessSource',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setRandomnessTimeout',
    inputs: [
      {
        name: 'seconds_',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setTreasury',
    inputs: [
      {
        name: 'treasury_',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sourceOfRequest',
    inputs: [
      {
        name: 'requestId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: 'source',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startDraw',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'topUp',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalCommissionOwed',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalEscrowed',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalPrizesOwed',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'treasury',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updateRaffle',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'prize',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'entryPrice',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'totalEntries',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'windowSeconds',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'walletCap',
    inputs: [
      {
        name: 'totalEntries',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'withdrawCommission',
    inputs: [
      {
        name: 'raffleIds',
        type: 'uint256[]',
        internalType: 'uint256[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'CommissionWithdrawn',
    inputs: [
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DrawStarted',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'requestId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'source',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Drawn',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'winner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'winningEntry',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'prize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'commission',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Entered',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'wallet',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'count',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
      {
        name: 'paid',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EntriesPausedChanged',
    inputs: [
      {
        name: 'paused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferStarted',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PrizeClaimed',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'winner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RaffleCancelled',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'refunded',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RaffleCreated',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'prize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'entryPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalEntries',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'windowEnds',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RaffleUpdated',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'prize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'entryPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalEntries',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'windowEnds',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RandomnessReRequested',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'oldRequestId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newRequestId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RandomnessSourceChanged',
    inputs: [
      {
        name: 'source',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RandomnessSourceScheduled',
    inputs: [
      {
        name: 'source',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'activatesAt',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RandomnessTimeoutChanged',
    inputs: [
      {
        name: 'seconds_',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ReadyToDraw',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'entriesSold',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'StaleFulfilmentIgnored',
    inputs: [
      {
        name: 'requestId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ToppedUp',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TreasuryChanged',
    inputs: [
      {
        name: 'treasury',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WindowExtended',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'windowEnds',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AlreadyStarted',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'entriesSold',
        type: 'uint32',
        internalType: 'uint32',
      },
    ],
  },
  {
    type: 'error',
    name: 'EntriesArePaused',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidEntryCount',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidEntryPrice',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidPrize',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidWindow',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NoEntriesYet',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotCompleted',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotDrawing',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotEnoughEntriesLeft',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'left',
        type: 'uint32',
        internalType: 'uint32',
      },
      {
        name: 'wanted',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotOpen',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotReadyToDraw',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotTheSource',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'caller',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotTheWinner',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'caller',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
  {
    type: 'error',
    name: 'NotYetActive',
    inputs: [
      {
        name: 'activatesAt',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
  },
  {
    type: 'error',
    name: 'NothingOwed',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NothingScheduled',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
  {
    type: 'error',
    name: 'OwnershipCannotBeRenounced',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PotCannotCoverPrize',
    inputs: [
      {
        name: 'pot',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'prize',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'PrizeAlreadyPaid',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'PrizeNotCovered',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'collected',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'prize',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
    inputs: [],
  },
  {
    type: 'error',
    name: 'RequestNotStale',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'staleAt',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
  {
    type: 'error',
    name: 'WalletCapReached',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'held',
        type: 'uint8',
        internalType: 'uint8',
      },
      {
        name: 'wanted',
        type: 'uint8',
        internalType: 'uint8',
      },
    ],
  },
  {
    type: 'error',
    name: 'WindowStillOpen',
    inputs: [
      {
        name: 'raffleId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'windowEnds',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
  },
  {
    type: 'error',
    name: 'ZeroAddress',
    inputs: [],
  },
] as const;
