#!/usr/bin/env node
/**
 * Copy the compiled ABIs into `packages/shared` as TypeScript.
 *
 * Generated rather than hand-written, because a hand-copied ABI drifts the
 * moment the contract changes and the failure is silent: calls encode against
 * a signature the deployed contract no longer has. `pnpm generate:abi` after
 * `forge build`, and CI checks the result is current.
 *
 * The output is committed so the app and the API can be built without Foundry.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'packages/shared/src/abi';
const CONTRACTS = [
  ['StubbyRaffle', 'stubbyRaffle'],
  ['D20RandomnessAdapter', 'd20RandomnessAdapter'],
];

mkdirSync(OUT, { recursive: true });

for (const [contract, name] of CONTRACTS) {
  const artifact = JSON.parse(
    readFileSync(join('packages/contracts/out', `${contract}.sol`, `${contract}.json`), 'utf8'),
  );
  const body = `/**
 * ABI for ${contract}.
 *
 * GENERATED by scripts/generate-abi.mjs — do not edit. Run \`pnpm generate:abi\`
 * after changing the contract.
 */
export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  writeFileSync(join(OUT, `${name}.ts`), body);
  console.log(`  ${contract} -> ${OUT}/${name}.ts (${artifact.abi.length} entries)`);
}

writeFileSync(
  join(OUT, 'index.ts'),
  CONTRACTS.map(([, name]) => `export * from './${name}.js';`).join('\n') + '\n',
);
